version: '3'
services:
  apollo:
    build:
      context: ./apollo
      dockerfile: Dockerfile
    environment:
      # NODE_ENV=production
      # - PRISMA_ENDPOINT:'${PRISMA_ENDPOINT}'
      PRISMA_ENDPOINT: '${PRISMA_ENDPOINT}/${RISMA_SERVICE_NAME}/test'
      PRISMA_SECRET: '${PRISMA_SECRET}'
      APOLLO_PORT: '${APOLLO_PORT}'
      JWT_SECRET: '${JWT_SECRET}'
      PRISMA_MANAGEMENT_API_SECRET: '${PRISMA_MANAGEMENT_API_SECRET}'
    volumes:
      - ./apollo/src:/app/src
    ports:
      - '${APOLLO_PORT:-8000}:${APOLLO_PORT:-8000}'
    command: sh -c "npm install -g nodemon && nodemon src/index.js"
  prisma:
    image: prismagraphql/prisma:1.34.10
    restart: always
    ports:
      - '${PRISMA_PORT:-4454}:${PRISMA_PORT:-4454}'
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        secret: ${PRISMA_SECRET}
        port: ${PRISMA_PORT:-4454}
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: ${PG_USER}
            password: ${PG_PASSWORD}
            migrations: true
  postgres:
    image: postgres:12.2
    environment:
      POSTGRES_USER: ${PG_USER:-prisma}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-prisma}
    volumes:
      - postgres:/var/lib/postgresql-prisma/data
volumes:
  postgres: ~
